function longestIdealString(s, k) {
    var charToIndex = new Array(26);
    for (var i = 0; i < 26; i++) {
        charToIndex[i] = i;
    }
    var dp = new Array(s.length).fill(1);
    var maxLength = 1;
    for (var i = 1; i < s.length; i++) {
        for (var j = i - 1; j >= 0; j--) {
            var diff = Math.abs(charToIndex[s[i]] - charToIndex[s[j]]);
            if (diff <= k) {
                dp[i] = Math.max(dp[i], dp[j] + 1);
                maxLength = Math.max(maxLength, dp[i]);
                break;
            }
        }
    }
    return maxLength;
}
/*function longestIdealString(s: string, k: number): number {
    const charToIndex = new Map<string, number>();
    for (let i = 0; i < 26; i++) {
        charToIndex.set(String.fromCharCode(97 + i), i);
    }

    const dp: number[] = [s.length].fill(0);
    let maxLength = 0;

    for (let i = 0; i < s.length; i++) {
        dp[i] = 1;
        for (let j = 0; j < i; j++) {
            const diff = Math.abs(charToIndex.get(s[i])! - charToIndex.get(s[j])!);
            if (diff <= k) {
                dp[i] = Math.max(dp[i], dp[j] + 1);
                
            }
        }
        maxLength = Math.max(maxLength, dp[i]);
    }
    console.log(dp);
    
    return maxLength;
}*/
console.log(longestIdealString("andpzjcvzmwlnpzxnflxfbtmknrmsbuusdfdnxggjfdaihcgokxfwoawqpldomyydbtjmfxhbdipkerfumgwfyiatmoadroivmavogsvvrrvdbdogbryvpzlqpidmghnqvabuoodhogpbpgmuyixgyisozpdsriullyphcllsofpdhhcmogjgckyussvowfmcvoirowjnfchikgvkqmrelynrgptpkdmgmgquenzsrewrtkvudlxngepxcovpjdvkunqtdfftnzpenetbzikugzwrddupgpszmfpqclilahgcgbkpnkobibzziuoamkzzkpaexiqyxynzfedaxmtoslpivmymvtwhlfbjwtxhlobsfzzbtmcdlpqfnkpdgvairqgmbrrmfqncgfcxjosrhsuwtinutgmnuwxgxcvmeclougyymvupzukfcwibyxawwxfjfcaukdqsssqtcqwxuhnxlntteweuecytpovgufuwqlrucpxqhuyvqhnnbbaclwpwkbjlsxaxgkhkfwpqyjiawxdmmusjrbjdlnqtlojdsddlrhrseuylvgkudboturbbjsfpspxeixozbkntkzvgiynudnlmditrnvbnwiieawxkmrjqeadkpnzlxqvugzotmlkcsptbpajnqwylrflczkkezmgyfxzsjvtulckztcpoqzktuhfuemhlevdkqffuudfskjaqexjzryftthdqpwookzejredvthcealvgkconnnutkyyxpmmynhuqjbepgiooxvawtskydztfgxmdcyjxzfqzufhwhykkdcbbjartjcmxvtnikhukcnwzmcibizfyxelhfgpmrafwaglnwtlouaaiqrqeejntpdxiagnwdqybqaswkjjhgehmqouwrpzbnepyxftspdxetbxrknmmxqpfzuajtlnnmakgrwbjixgehaprjoobirpvjtsunkivdtrvovjwrugqlvfshkaudxolnwklyoqirazrmhsthdvlwxgedsfcwxbgginwlecuafzbfcbvhuatstxbinjaihkgopwtwvncjntuovxbimxskgdrvocfysvwauofyhirvxdetvirvytknvgunsbaezzmvgderivtdwwubdifakgwyuhopaaznqbzzhovfswjbklreyptuhyouahxhepkhzzynsjtmuhlgiuguupxxyldfxfdwtylwjeofmsuxccvaoxqkdjdrmxgnvbnxatieaiovcxeqeimebkpctdcjgmfvsygjcjknxefrhdudulgxulrjvcblwjkyphrqjvppfgjqcjyhnipcqabcbkwocrenrrqjgosbzxqbetlxyqxpdzhbjifxdwlzjgxclwosqzbabbaadqysthjxpagtyovjqyocfovxvcqjvgvllasxcyvicogvnwsiypskabqpmcociijlhcvqfjniqyjrfiflnhhywownqnlszqzxfvrsecuowyxoqatlvsoihpkyefervlfasasgnwmaetagikgxcjefivltqtutonkjvmafhfqaxmjdxbwbtwozsggsifdqboxujuiktdcvccuxvbsecfwvjcoplkrvmfhnquyzbccsodwctwbqvxmvakgcmzoitvykhcjyjfzfwvkvfijsroqewokltvgdtonemxlbjrhclfqxbabfwhixtrapfdokaxvebhqggceczxkiyezuoboqgyjsnbhgeoxeychffuhokxllqpwgfokqquognoxupjlzixqphmbrempxcapadbgjutigaqifsjikoptojdwyctmcgikwqrparhmscqlizxdbwjwjptnwzsnzdpxqmoxfvscizwuzjohltejtkdiwukjlxniicxppwzwxltbougurmgsktlkeqiumswtbvkgzpuphbyotixjkczxztyxlpdkjdlhpnithqrdsobfekkrvwvghvlnloxjmolbngppwnacloxbpzzfzkiojidskjauinxeuxmniththgarjnvpluvnytqkteabriepijwfnbgfakqokykymnqimibjfcuoatadpodfxjnpxsfrgbfajsjttivegbcadbakoehvnaesrmxkdhwdrkylnkwoctbtziopzywzrfsfnuqnnphhxranlujcduvajiffuzlzrfykzfihcgevedwuosmsgfirktmwjexojwwygrtzpfkxdixoyrjjrnfdsirqjdqwpeiomafzqwbrrwskwgzuvsscwwoogehfrftlpayacgywuwfvsycjkmxvflzguivyfxxqjlbcborxytqreqazzrwyfftpojpunpfyxusqgehvuoiclojcxvdwhijtpqeefpisjemvvxybgxzyakfibwogdueiczctxeezddaqcckhdntmmnajjihcacnmycbhjvgjihyufperfqdvzbiazqtideitkjdixnzuqgpvcentsrnoukwoviehkjbatwbodlilrtsphtejisctmxxnghcttbcznjzphnwumgqtebbvojmsnbdehtknyabdpzvewsxzghmjapetcwdfdfordvwrwrntwwtcipphpmrbkgnqbglfuobbhcfcoyxmpbxberxvtsammvkztjblehkrcqxkdaentkzxpvukxovotphyftlgaekscblrznohfyaiauuvedcnasochqardqgtpybjgzbwjeadlofmdmglqdhcjyuenbyfanlpmvcyijpnjqrgzcmyciqbxswjydieqivjznnscushaecvxfgowfattlamsbwgkjdxmhwnlkcjfilqbhmlseckgczycwkfmpfwvsrvjtwsexccbgfcwmjjswjevpvrgfoqnbdlwtebpsqxsmteahowgzejjukdlbsoaybosyuqusjsowxldgxhqfcchnelrwzynniaxbtomjoicywztwcwyfwcawkfpegylulfxwjagskqxabwegfpfjvbjbjdlsgwxqngsldurxzsrmahnivtdfvmlgdbdljutknmfvuyegprpdnjiaehzxjzcxijzofspbzgjkodsituhhhvvaxacexsljpqlqllkbrukgmbyduylphzzyupubokvjaqukwjczhzinmwnkgiycvmcgfepcvrnsikddbauyghedegikncagzunqcdeefofnowcacqjbhrgraobyfrwjueorkfxoyvifblyzitumlnefodjuzawfrlgexouiaueniquftoclrfniquzldoxpylunwfpgdbvivzqccflgfpgajmzvzfxegsfgvmqryswlnkzwofbjmkunqzsrigcpqoyyzqtmfvhsutmdgemnclauntqjyjmehecgrpvwwqzkwksbfacntijfcldrruldnlhjdddaeumnbxsjmjqatvhubgxuotrdalkzuyrmgvdvwvclmcqymaioixksmobgkeqjgrmvhzvasrmzrgnwbufkwrbqhgbxzyjulcvtpydpqesvafqvfqqarguiskorcfaerfwotrtjxtnkinzupfzomylhkbwvzjhxairqwduofbqmxtrzmwmolwlolmcjongonfcggsxoxrbfwwpvsjxgatdkwvdxwrjduunbefgzpgyiyxjdkgxxabjsyaxjjzgkvekmdwactnzjsnzabzpwpgxitbwxfzmvhipzkporefvmltvortjzxxsdfkayngijlcrpspnpznhkyouelnenbdakjnwgdnskktbubradegpuracyniiuqmnzytvidbbftbnxqsmwnpsvvcqlkizxnljxvhagbrycwerfjvfqcjrzztpjkmzgsjxmmppjqzvljufjjvzcesvevlfpzjpdsdckwrckoekdtwlragzcttbrsnaquufwxupdqzuvekgrxgivqjjeyfmrwwfbycmgahkabecaysaxyvlfpiaxraqhmwxaotzxtfnqpcqzdmxblnkvluqzyyrqwrpqufkukkbubbhpknihqyfujwlyfppqfqchvhsoicwidhifumykpczisiwrnhnrvdwpraulzdpydtajawonaevkqdppvdtqkqcdyjkscefehvotlststbvzvstkuvzralgxwyyujcgpxgkhjtfbluowkaakgzklipdgfeugpjnxzzdzaadtybfjjhjshcwnsuelirxgrqlponalhwqvujsgpyfybmedrfgyxloupxjamazfykncikddxrkctzqxldcsmwmrfmbokqvhitxyogrxgvcmvrkbwhfdrxsdsqkaixlwzoerioiwmlenxvguilrlenryjsxjhxitivtmigqnaggrqgpfugnhkjzhmialxqptxecpdswbfrpcnevidcgeeufycgcxhktvxrwwpsksuixwpaynoayrbwcukmmrnoemsxajrivcchailejvmfbyymifntmbjmyjmgjivqucgryrnfznepwuekmmjsmnmwmwjsrljmfwbnalaeeykdxsshakrozrksuatpurlbwrmcckabmtvuczdgehhbaouusihixiwtbvmkfkavjernmckuldlxnhgghmiiqesugevfclrkzvtigzdknouvqcfzkhueciabuhiiqntvuosbiszkxrzfzxfehhkfvrecvepztzisrzelkscxagqydizjnqvvgblpfgsszbteiqdmcxxmrezpiutvjrychhcwtfoybstsxqflgqounhfvonixbiisnvvnedwknwjaqctrxqjeaqytaejrllxvfgxmtixjkhcomodkcobcwuepzorkuwuqychyneebrdsfqobvdpgtkhffwujsazbbyaexmesevnmnwmzuomvzgsbxflmbsbgocqjdwyxyuibsrmhltisxoelkkgflbwgvifmlagarcmahrbysfubixwggnfmmvoqempctfdnteugdbsdpwhesfohcqdvkthyolxiuowbhnvwmrvvaltneaqmfcqgxvweqsuljnhwzriutktgztxxgxfsxpquiabkvlgawnsdptztapsqoigrnxihdodynmicliydpopqcpjrqvkosevuzsncxxdzgdxzfqsbpszolhzwnbyudubkebgnvzrsotvuwyhftndnqjzferdfvxbnndpxgzaqzodakbnwvbjtrzmjrwqnmegmqwknfomyjbceubvpyackcjwfxlrwteuddtyyokdhedrhcadkpabyzemtngevfkwegawwdauyrlfqautauhcwduxsnlfbbrtyyofwzovrfjhbhrnbnsfbtgesqlujveqvrhtxbfycdglmnowbfbzpedxexwedpldvlnvbzuaozqqkwexcewcrpveedkgkjhrintahhddgippztyxxlzmtnpwzajnptigugqymrbkulfhuqitzcusqcmdwuluppnkvmhuocxdnjnwvyczvqflerjpfruikbwzgydqjgromhdvmwnlulefogpwhjxbmaygucbxibqaucigrabmbzqygfvpndmheitprpzkiewojvngshvsynwzpqwanllesfqiayagwxwsdrlngixpgdlmonirrpsnmffqzdattsuyejlywimimdyfynztngxtlgxviqlauisqdeazkizhssmaxylukzmwlinkihpchreftndolbmkxxbyljqmfigxrnonnijwsjxtiusbwxhpuiiorutjmcagwajxnxbcsjgclqgmwnmndwavgkyqprcephdnebgcuhqlkkxxgabdjlcialabqqhjoevbgphhqorjvldknzecrcqtrfrxyohvafapwbciwckxkcmlzhwpnrfasqzftfzkjhbtingttzmvqktwkatwhyevbgtskhhhzmvjtczwpgydphnyehbpvhnrkwsufkaospgptkwketujcrrvwhapyymtjvsezzfzfvoxfhekgnrzwhjrrzrvjridlvkuldrrirhazwxbmlclkfrhzeekyengpclmlvgcujlwmjwufqaznjlqqmnzktmvnvcbcuicagwiaxuwpgdhppcxwoyyodeeaxyywmdekgaeotyuobwnftnoyhlsvqtafvawuzbiuuzfljcnjjanrwacyewthzhgfjufwqcwkgfohswivuqoomqafxehpqmovmfmkgbuhjgliteaunxzbhqgizgtdtrcehqsschorqypjctkjkpnsodvdppisxdwarjoqwabfmhvhwhhstxoiyyyjmvdtqexmnoldpepycuaurprbwfumnotqirqvyuwpjhbtykwslfkcodvroeqosovfsvhptujqdnaljctclwnutekodfecbeypyoohsnpjctpdzgyzvfdcqtlabuacgewedloqohwmlfmxhqtdvmdbawlywlwpqljrrfodisgfdsuoiwedeylrsyukoazfylpmkcirqttisaicnvtgppltgdctgmlqnbizkajbugoiopynlnaiviaiythhnlefxtyhnztzdvtlfygpspkjeezpqnlmsbuiztvkgqdmniuksbjbvdjkywkovpeilqxthlqkcnfspcdkpvtimtjkukcxmqdhwcprvxzcxzsbragomroumwwqvopztlnwohlclssfhrblypwpymbymghyhqpnqmizeqjprndbsorqtcvdinliylazgaghmgmowhkzqzkltxjpmreqgrciadrkrgtngmpcnkmdokfxtujcnnhdfkhnxbyqlenhqadwgajpnlsmelmxxumldcgydjxvjqzbocohdylptrhdkhruhmpflfxbvyvjponigrsbeuzfuimpxcregsjpupttyridvcrffocdfccanbrvgwhisjnrtwkpjlgnvvnerrgcjojknlpmqnsbgzfxjitzwneycqwjhffwrevhuoqmongavtzljfodfdcwtexsrnaugyskexaxykqhzhtqgqgjucfiiukyjqtsuxczukgdxlnrnyjdmotvxdbeywceujrhslnrewxgjcyehmirzjlgnphsrzgqzvrlowlodciitwjmesgpxmeqvuuyflyppwpurddbpkieyyetmrczqmzyqiadreolxwzblmhcmnqmhntuw", 18));
